name: 'Build and Deploy to Cloud Run'
on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'py-api-457416'
  REGION: 'europe-north2'
  SERVICE: 'py-api'
  GAR_NAME: 'py-api'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 
      - name: 'Google Auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
      - name: 'Deploy to Cloud Run'

        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}'
          env_vars: |
            API_KEY=${{ secrets.API_KEY }}
            AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            PROJECT_ID=${{ secrets.PROJECT_ID }}
            STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}
            MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}
            APP_ID=${{ secrets.APP_ID }}
            MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
